name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Snacks.Entity.Core/Snacks.Entity.Core.csproj
        VERSION_FILE_PATH: src/Shared/base.props
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Snacks.Entity.Authorization/Snacks.Entity.Authorization.csproj
        VERSION_FILE_PATH: src/Shared/base.props
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        # Build directory to deploy
        build_dir: Documentation/_site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}